export const RACUN_URL = 'http://localhost:8080/racun'
export const PROIZVODJAC_URL = 'http://localhost:8080/proizvodjac'
export const PROIZVOD_URL = 'http://localhost:8080/proizvod'
export const STAVKA_RACUNA_URL ='http://localhost:8080/stavkaRacuna'
export const STAVKE_RACUNA_ZA_RACUNID_URL = 'http://localhost:8080/stavkaRacuna/racun'
