export const RACUN_URL = 'https://rva-andrea.herokuapp.com/racun'
export const PROIZVODJAC_URL = 'https://rva-andrea.herokuapp.com/proizvodjac'
export const PROIZVOD_URL = 'https://rva-andrea.herokuapp.com/proizvod'
export const STAVKA_RACUNA_URL ='https://rva-andrea.herokuapp.com/stavkaRacuna'
export const STAVKE_RACUNA_ZA_RACUNID_URL = 'https://rva-andrea.herokuapp.com/stavkaRacuna/racun'
